### PR TITLE
Update lodash functions

### PR DESCRIPTION
**Pull request by pgilad**

### CODE REVIEW

**Comment by othree** [comment]
Is this base on v3.9.3 ?

**Comment by pgilad** [comment]
I think it's redundant to keep track of versions, because in the end what should happen in going to lodash site and running `_.methods(_)` (Currently there are 217).
It'll be much easier to track then...

But yeah I think it's based on 3.9.3

**Comment by othree** [comment]
Version number is used to see is there might have any new stuff. They add new method, but also remove methods.

**Comment by pgilad** [comment]
That's why I advocate for clearing version number, and simply running:
```js
_.methods(_);
```
In the lodash site to get all the exported functions. That why it can be updated occasionally and lodash usually saves the aliases intact (`extend => assign`, `each => forEach`, etc...)

**Pull request merged**
